[build] 
  command = "CI=false yarn build"

[context.production]
  publish = "build/"
  [context.production.environment]
    REACT_APP_API_URL = "https://api.guimochila.com"

[[redirects]]
  from = "/*"
  to = "index.html"
  status = 200
